INSERT INTO family(fa_familyName,or_id)
VALUES
    (
        "TINAMIDAE",1,1
    ),
    (
        "ANHIMIDAE",2,2
    ),
    (
        "ANATIDAE",3,2
    ),
    (
        "CRACIDAE",4,3
    ),
    (
        "ODONTOPHORIDAE",5,3
    ),
    (
        "PODICIPEDIDAE",6,4
    ),
    (
        "PELECANIDAE",7,5
    ),
    (
        "SULIDAE",8,6
    ),
    (
        "PHALACROCORACIDAE",9,6
    ),
    (
        "ANHINGIDAE",10,5
    ),
    (
        "FREGATIDAE",11,6
    ),
    (
        "ARDEIDAE",12,5
    ),
    (
        "THRESKIORNITHIDAE",13,7
    ),
    (
        "CICONIIDAE",14,7
    ),
    (
        "CATHARTIDAE",15,11
    ),
    (
        "PHOENICOPTERIDAE",16,9
    ),
    (
        "PANDIONIDAE",17,11
    ),
    (
        "ACCIPITRIDAE",18,10
    ),
    (
        "ARAMIDAE",19,12
    ),
    (
        "RALLIDAE",20,12
    ),
        "CHARADRIIDAE",21,13
    ),
    (
        "RECURVIROSTRIDAE",22,13
    ),
    (
        "BURHINIDAE",23,13
    ),
    (
        "SCOLOPACIDAE",24,13
    ),
    (
        "JACANIDAE",25,13
    ),
    (
        "LARIDAE",26,13
    ),
    (
        "RYNCHOPIDAE",27,13
    ),
    (
        "COLUMBIDAE",28,14
    ),
    (
        "PSITTACIDAE",29,15
    ),
    (
        "HAEMATOPODIDAE",30,13
    ),
    (
        "CUCULIDAE ",31,16
    ),
    (
        "TYTONIDAE",32,17
    ),
    (
        "STRIGIDAE",33,17
    ),
    (
        "NYCTIBIIDAE",34,18
    ),
    (
        "CAPRIMULGIDAE",35,18
    ),
    (
        "APODIDAE",36,19
    ),
    (
        "TROCHILIDAE",37,19
    ),
    (
        "ALCEDINIDAE",38,20
    ),
    (
        "MOMOTIDAE",39,20
    ),
    (
        "GALBULIDAE",40,22
    ),
    (
        "BUCCONIDAE",41,22
    ),
    (
        "RAMPHASTIDAE",42,21
    ),
    (
        "PICIDAE",43,21
    ),
    (
        "THAMNOPHILIDAE",44,21
    ),
    (
        "FURNARIIDAE",45,21
    ),
    (
        "TYRANNIDAE",46,21
    ),
    (
        "PIPRIDAE",47,23
    ),
    (
        "TITYRIDAE",48.23
    ),
    (
        "VIREONIDAE",49,23
    ),
    (
        "CORVIDAE",50,23
    ),
    (
        "HIRUNDINIDAE",51,23
    ),
    (
        "TROGLODYTIDAE",52,23
    ),
    (
        "POLIOPTILIDAE",53,23
    ),
    (
        "DONACOBIIDAE",54,23
    ),
    (
        "TURDIDAE",55,23
    ),
    (
        "MIMIDAE",56,23
    ),
    (
        "THRAUPIDAE",57,23
    ),
    (
        "EMBERIZIDAE",58,23
    ),
    (
        "CARDINALIDAE",59,23
    ),
    (
        "PARULIDAE",60,23
    ),
    (
        "ICTERIDAE",61,23
    ),
    (
        "FRINGILLIDAE",62,23
    ),
    (
        "CAPRIMULGIDAE",63,18
    ),
    (
        "TROCHILIDAE",64,19
    ),
    (
        "FALCONIDAE",65,11
    );
