INSERT INTO species (sp_CientificName,sp_vulgarName,ge_id,es_id,ha_id, img_id)
VALUES
    ("Tinamus major","Tinamú Grande",1),
    ("Crypturellus erythorpus","perdiz de patas rojas",2),
    ("Chauna chavarria"," chicagüire",3),
    ("Dendrocygna bicolor","suirirí bicolor",4),
    ("Dendrocygna viduata","yaguasa de cara blanca",4),
    ("Dendrocygna autumnalis","Suirirí piquirrojo",4),
    ("Cairina moschata","Cairina moschata",5),
    ("Anas bahamensis","pato gargantilla",6),
    ("Anas discors"," Barraquete Aliazul",6),
    ("Nomonyx dominicus","Pato Enmascarado",7),
    ("Ortalis garrula","guacharaca caribeña",8),
    ("Ortalis ruficauda","Guacharaca Guajira",8),
    ("Penelope purpurascens","pava cojolita",9),
    ("Colinus cristatus","colín crestudo",10),
    ("Tachybaptus dominicus","Zambullidor Menor",11),
    ("Podilymbus podiceps","Zambullidor Pico Grueso",12),
    ("Pelecanus occidentalis","Pelícano Pardo",13),
    ("Sula leucogaster","Piquero Pardo",14),
    ("Phalacrocorax brasilianus","Cormorán Neotropical",15),
    ("Anhinga anhinga","Pato aguja",16),
    ("Fregata magnificens","fragata común",17),
    ("Tigrisoma lineatum","Vaco Colorado",18),
    ("Trigrisoma fasciatum","Vaco Cabecinegro",18),
    ("Cochlearius cochlearius","Garza Cucharón",19),
    ("Ixobrychus exilis","Avetorillo Bicolor",20),
    ("Ixobrychus involucris","mirasol chico",20),
    ("Nycticorax nycticorax","Guaco Común",21),
    ("Nyctanassa violacea","Guaco Manglero",240),
    ("Butorides virescens"," Garcita Verde"22),
    ("Butorides striatus","Garcita Verdosa",22),
    ("Bubulcus ibis","Garzita Bueyera",23),
    ("Ardea herodias","Garza Morena",24),
    ("Ardea cocoi","Garza Mora",24),
    ("Ardea alba","Garza Real",24),
    ("Pilherodius pileatus","garza pileada",25),
    ("Egretta rufescens","Garza Rojiza",26),
    ("Egretta thula","Garza Dedos Dorados",26),
    ("Egretta caerulea","Garceta Azul",26),
    ("Eudocimus albus","Corocora Blanca",27),
    ("Eudicimus ruber","Corocoro Rojo",27),
    ("Plegadis falcinellus",28),
    ("Mesembrinibis cayennensis","Tapicurú",29),
    ("Phimosus infuscatus","Coquito",30),
    ("Theristicus caudatus","Bandurria Boreal",31),
    ("Platalea ajaja","Espátula Rosada",32),
    ("Jabiru mycteria","Cigüeña Jabirú",33),
    ("Mycteria americana","Cigüeña Americana",34),
    ("Cathartes aura","Guala Cabecirroja",35),
    ("Cathartes burrovianus","Zopilote Sabanero",35),
    ("Coragyps atratus","Chulo",36),
    ("Sarcoramphus papa","Rey de Los Gallinazos",37),
    ("Phoenicopterus ruber","Flamenco Americano",38),
    ("Pandion haliaetu","Águila Pescadora",39),
    ("Elanus leucurus","Gavilán Maromero",40),
    ("Gampsonyx swainsonii","Elanio Enano",41),
    ("Chondrohierax uncinatus","Caracolero Selvático",42),
    ("Leptodon cayanensis","Gavilán Cabeza Gris",43),
    ("Elanoides forficatus","Milano Tijereta",226),
    ("Rostrhamus sociabilis","Gavilán Caracolero",44),
    ("Ictinia plumbea","Milano Plomizo",45),
    ("Ictinia mississippiensis","Milano de Mississippi",45),
    ("Accipiter bicolor","Gavilán Bicolor",46),
    ("Geranospiza caerulescens","Gavilán Zancón",47),
    ("Buteogallus anthracinus","Aguililla Negra Menor",48),
    ("Buteogallus urubitinga","Aguililla Negra Mayor",48),
    ("Buteogallus meridionalis","Gavilán Cangrejero Colorado",48),
    ("Busarellus nigricollis","Aguililla Canela",49),
    ("Rupornis magnirostris","Gavilán Pollero",50),
    ("Parabuteo unicinctus","Águila Rabiblanca",51),
    ("Geranoaetus albicaudatus","Águila coliblanca",52),
    ("Asturina nitida","Aguililla Gris Meridional",53),
    ("Buteo platypterus","Águila Migratoria",227),
    ("Buteo brachyurus"."Águila rabicorta",227),
    ("Buteo albonotatus"."Águila gallinaza",277),
    ("Caracara cheriway"."Guaraguaco Común",54),
    ("Milvago chimachima","Pigua",55),
    ("Herpetotheres cachinnans","Halcón Culebrero",56),
    ("Micrastur semitorquatus","Halcón Collarejo",57),
    ("Falco columbarius","Esmerejón",58),
    ("Falco rufigularis","Halcón Murcielaguero",58),
    ("Falco femoralis","Halcón Plomizo",58),
    ("Falco perigrinus","Halcón Peregrino",58),
    ("Aramus guarauna","Carrao",59),
    ("Aramides cajanea","Chilacoa Colinegra",60),
    ("Laterallus exilis","Laterallus exilis",61),
    ("Porzana flaviventer","Polluela de Antifaz",62),
    ("Porzana albicollis","Polluela Cienaguera",62),
    ("Porzana carolina","Polluela Migratoria",62),
    ("Gallinula chloropus","gallineta común",63),
    ("Porphyrio martinica","Polla Azul",64),
    ("Fulica americana","focha americana",228),
    ("Vanellus chilensis","Pellar Común",65),
    ("Pluvialis squatarola","Chorlo Pechinegro",66),
    ("Charadrius semipalmatus","Chorlito Semipalmeado",67),
    ("Charadrius wilsonius","Chorlito Piquigrueso",67),
    ("Charadrius alexandrinus","Chorlitejo Patinegro",67),
    ("Charadrius collaris","Chorlito Collarejo",67),
    ("Haematopus palliatus","Ostrero",68),
    ("Himantopus mexicanus","Cigueñuela",69),
    ("Recurvirostra americana","avoceta americana",229),
    ("Burhinus bistriatus","Alcaraván",70),
    ("Gallinago delicata","Caica Común",71),
    ("Limnodromus griseus","Becasina Piquicorta",230),
    ("Limnodromus scolopaceus","Becasina Piquilarga",230),
    ("Numenius phaeopus","ZARAPITO COMÚN",72),
    ("Barthramia longicauda","Correlimos Sabanero",73),
    ("Actitis macularia","Andarríos Maculado",74),
    ("Tringa melanoleuca","Andarríos Mayor",75),
    ("Tringa flavipes","Patamarilla Menor",75),
    ("Tringa solitaria","Andarríos Solitario",75),
    ("Tringa semipalmata","Playero Aliblanco",75),
    ("Arenaria interpres","Vuelvepiedras",76),
    ("Calidris canutus","Correlimos Colorado",77),
    ("Calidris alba","Correlimos Blanco",77),
    ("Calidris pusilla","Correlimos Semipalmeado",77),
    ("Calidris mauri","correlimos de Alaska",77),
    ("Calidris minutilla","Correlimos Diminuto",77),
    ("Calidris fuscicollis","Correlimos Rabiblanco",77),
    ("Calidris ferruginea","correlimos zarapitín",77),
    ("Jacana jacana","Gallito de Ciénaga",78),
    ("Leucophaeus atricilla","Gaviota Reidora",79),
    ("Sternula superciliaris","Gaviotín Fluvial",80),
    ("Phaetusa simplex","Gaviotín Picudo",81),
    ("Gelochelidon nilotica","Gaviotín Blanco",82),
    ("Hydroprogne caspia","pagaza piconegra",83),
    ("Chlidonias niger","Gaviotín Negro",84),
    ("Sterna hirundo","Gaviotín Común",85),
    ("Thalasseus sandvicensis","Gaviotín Patinegro,86"),
    ("Thalasseus maximus","Gaviotín Real",86),
    ("Rynchops nigra","Rayador",87),
    ("Columbina passerina","Tortolita Pechiescamada",88),
    ("Columbina minuta","Tortolita Diminuta",88),
    ("Columbina talpacoti","Tortolita Común",88),
    ("Columbina squammata","Tortolita Colilarga",88),
    ("Claravis pretiosa","Tortolita Azul",89),
    ("Patagioenas corensis",""Torcaza Cardonera,90),
    ("Patagioenas cayennensis","Torcaza Morada",90),
    ("Patagioenas plumbea","Torcaza Plomiza",90),
    ("Zenaida auriculata","Torcaza Naguiblanca",91),
    ("Leptotila verreauxi","Leptotila verreauxi",92),
    ("Ara ararauna", "guacamayo azulamarillo",232),
    ("Ara macao", "guacamayo rojo",232),
    ("Ara chloroptera", "guacamayo aliverde",232),
    ("Aratinga pertinax", "perico cara sucia",(Arteta)),
    ("Forpus passerinus", " periquito",233),
    ("Forpus xanthopterygius", "cotorrita aliazul",233),
    ("Forpus conspicillatus", "periquito de anteojos"233),
    ("Brotogeris jugularis", "Periquito Bronceado",93),
    ("Pionus menstruus", "Cotorra Cheja",94),
    ("Amazona autumnalis", "loro cariamarillo",95),
    ("Amazona ochrocephal", "Lora Común",95),
    ("Amazona amazonica", "loro guaro",95),
    ("Coccyzus pumilus", "Cuclillo Rabicorto",96),
    ("Coccyzus americanus", "Cuclillo Migratorio",96),
    ("Coccyzus melacoryphus", "cuco de pico oscuro",96),
    ("Coccyzus lansbergi", "Cuclillo Canelo",96),
    ("Piaya cayana", "cuco ardilla",97),
    ("Crotophaga major", "garrapatero mayor",98),
    ("Crotophaga ani", "Garrapatero Común",98),
    ("Crotophaga sulcirostri", "garrapatero asurcado",98),
    ("Tapera naevia", "cuclillo listado",99),
    ("Tyto alba", "lechuza de los campanarios",100),
    ("Megascops choliba", "currucutú común",101),
    ("Pulsatrix perspicillata", "Búho de Anteojos",102),
    ("Bubo virginianus", "Búho Real",103),
    ("Glaucidium brasilianum", "Buhíto Ferrugineo",104),
    ("Pseudoscops clamator", "Búho Rayado",105),
    ("Nyctibius griseus", "Bienparado Común",106),
    ("Chordeiles acutipennis", "Chotacabras Menor",234),
    ("Chordeiles minor", "Chotacabras Migratorio",234),
    ("Nyctidromus albicollis", "Guardacaminos Común",107),
    ("Antrostomus rufus", "Guardacaminos Colorado",108),
    ("Caprimulgus cayennensis", "guardacaminos rastrojero",109),
    ("Chaetura vauxi", "vencejo de Vaux",110),
    ("Chaetura meridionales", "Vencejo Sureño",110),
    ("Chaetura brachyura", "Vencejo Rabicorto",110),
    ("Colibri delphinae", "colibrí pardo",235),
    ("Glaucis hirsuta", "Ermitaño Canelo",111),
    ("Phaethornis augusti", "ermitaño gris",236),
    ("Phaethornis anthophilu", "ermitaño gris",236),
    ("Phaethornis superciliosus", "ermitaño colilargo común",236),
    ("Anthracothorax nigricollis", "Mango Pechinegro",112),
    ("Chrysolampis mosquitus", "Cabeza de Rubí",113),
    ("Chlorostilbon mellisugus", "esmeralda coliazul",237),
    ("Thalurania colombic", "zafiro coroniazul",114),
    ("Damophila julie", "Colibrí pechiverde",115),
    ("Lepidopyga coeruleogularis", "Colibrí gorgizafiro",116),
    ("Lepidopyga goudoti", "Colibrí de Goudot",116),
    ("Amazilia tzacatl", "Amazilia Colirrufa",117),
    ("Amazilia saucerottei", "Amazilia Coliazul",117),
    ("Megaceryle torquata", "Martín pescador de collar",118),
    ("Megaceryle alcyon", "Martín Pescador Norteño",118),
    ("Chloroceryle amazona", "Martín pescador amazónico",119),
    ("Chloroceryle americana", "Martín pescador verde",119),
    ("Chloroceryle aenea", "Martín pescador enano",119),
    ("Momotus momota", "Momoto común",120),
    ("Galbula ruficauda", "Jacamará colirrufo",121),
    ("Hypnelus ruficollis", "Bobito punteado",122),
    ("Ramphastos sulfuratus", "Tucán del Caribe",123),
    ("Picumnus cinnamomeus", "Carpinterito castaño",124),
    ("Melanerpes rubricapillus", "Carpintero Habado",125),
    ("Verniliornis kirkii", "Carpintero lomirrojo",126),
    ("Colaptes punctigula", "Carpintero Pechipunteado",127),
    ("Dryocopus lineatus", "Carpintero rea",128),
    ("Campephilus melanoleucos", "Carpintero Marcial",129),
    ("Sakesphorus canadensis", "Batará Copetón",130),
    ("Thamnophilus doliatus", "Batará Barrado",131),
    ("Thamnophilus melanonotus", "Batará dorsinegro",131),
    ("Myrmotherula axillaris", "Hormiguerito flanquialbo",132),
    ("Formicivora grisea", "Hormiguerito coicorita",133),
    ("Myrmeciza longipes", "Hormiguero ventriblanco",134),
    ("Furnarius leucopus", "hornero paticlaro",135),
    ("Synallaxis albescens", "Rastrojero Pálido",136),
    ("Synallaxis candei", "Rastrojero Bigotudo",136),
    ("Certhiaxis cinnamomea", "Rastrojero Barbiamarillo",137),
    ("Certhiaxis mustelinus", "Rastrojero Pechiblanco",137),
    ("Dendrocincla fuliginosa", "Trepador pardo",138),
    ("Dendroplex picus", "Trepatroncos piquirrecto",138),
    ("Xiphorhynchus guttatus"  , "Trepador Silvador",139),
    ("Campylorhamphus trochilirostris", "Guadañero Rojizo",140),
    ("Elaenia flavogaster", "fiofío ventriamarillo",141),  
    ("Elaenia chiriquensis", "Fiofío Belicoso",141),
    ("Elaenia frantz", "Fiofio montano",141),
    ("Camptostoma obsoletum", "Tiranuelo Silbador",142),
    ("Phaeomyias murina", "Piojito pardo",143),
    ("Capsiempis flaveola", "Tiranuelo Amarillo",144),
    ("Zimmerius vilissimus", "Mosquerito cejiblanco",145),
    ("Leptopogon amaurocephalu", "Orejero coronipardo",146),
    ("Sublegatus arenaruum", "Atrapamoscas rastrojero",147),
    ("Inezia tenuirostris", "Piojito picofino​",148),
    ("Inezia subflava" , "Piojito pantanero",148),
    ("Atalotriccus pilaris", "Mosquerito ojiblanco",149),
    ("Poecilotriccus sylvia", "Titirijí gris",150),
    ("Todirostrum cinereum", "Titirijí común",151),
    ("Todirostrum nigriceps", "Titirijí cabecinegro​",151),
    ("Rhynchocyclus olivaceus", "Picoplano oliváceo",152),
    ("Tolmomyias sulphurescen", "picoplano sulfuroso",153),
    ("Tolmomyias flaviventris", "Picoplano pechiamarillo​",153),
    ("Cnemotriccus fuscatus", "Mosquero parduzco",154),
    ("Empidonax (traillii-alnorum)", "Mosquero alisero​",155),
    ("Contopus virens", "Atrapamoscas Oriental",156),
    ("Contopus cinereus", "Atrapamoscas Oriental",156),
    ("Pyrocephalus rubinus", "Atrapamoscas Pechirrojo",157),
    ("Fluvicola pica", "Viudita Común",158),
    ("Arundinicola leucocephala", "viudita cabeciblanca",159),
    ("Machetornis rixosa", "Atrapamoscas Ganadero",160),
    ("Myiozetetes cayanensis", "Suelda Crestinegra",161),
    ("Myiozetetes simil", "Suelda Crestinegra",161),
    ("Pitangus sulphuratus", "Bichofué Gritón",162),
    ("Pitangus lictor", "Bichofué Chico",162),
    ("Conopias parvus", "Bienteveo guayanés",163),
    ("Myiodinastes maculatus", "Bienteveo rayado",164),
    ("Megarhynchus pitangua", "Atrapamoscas Picudo",165),
    ("Tyrannus melancholicus", "Sirirí común",166),
    ("Tyrannus savan", "Sirirí Tijereta",166),
    ("Tyrannus tyrannus", "Sirirí migrante",166),
    ("Tyrannus dominicensis", "Sirirí gris",166),
    ("Sirystes sibilator", "Suirirí silbón",167),
    ("Myiarchus tuberculifer", "Copetón capirotado",168),
    ("Myiarchus venezuelensis", "Copetón venezolano",168),
    ("Myiarchus panamensis", "Copetón panameño​",168),
    ("Myiarchus crinitus", "Copetón viajero",168),
    ("Myiarchus tyrannulus", "Copetón tiranillo",168),
    ("Chiroxiphia lanceolat", "Saltarín lanceolado",169),
    ("Manacus manacus", "saltarín barbiblanco"170),
    ("Pachyramphus rufus", "Anambé cinéreo",171),
    ("Pachyramphus polychopterus", "Anambé aliblanco",171),
    ("Cyclarhis gujanensis", "vireón cejirrufo",172),
    ("Vireo olivaceus", "Verderón Ojirojo",173),
    ("Hylophilus aurantiifrons", "Verdillo luisucho​",174),
    ("Hylophilus flavipes", "Verdillo paticlaro",174),
    ("Cyanocorax affinis", "Carriquí Pechiblanco",175),
    ("Tachycineta albiventer", "Golondrina aliblanca",176),
    ("Progne tapera", "Golondrina Parda",177),
    ("Progne chalybea", "Golondrina de Campanario",177),
    ("Atticora melanoleuca", "Golondrina acollarada",178),
    ("Pygochelidon cyanoleuca", "Golondrina Azul y Blanca",179),
    ("Stelgidopterix ruficollis", "Golondrina Barranquera",180),
    ("Riparia riparia", "Avión zapador",181),
    ("Hirundo rustica", "Golondrina común",182),
    ("Petrochelidon pyrrhonota", "Golondrina risquera",182),
    ("Troglodytes aedon", "Chochín criollo",184),
    ("Campylorhynchus zonatus", "Ratona de dorso franjeado",185),
    ("Campylorhynchus nuchalis", "Cucarachero chocorocoy",185),
    ("Campylorhynchus griseus", "Cucarachero currucuchú",185), 
    ("Thryophilus rufalbus", "Cucarachero cantor",186),
    ("Cantorchilus leucotis", "Ratona rojiza",187),
    ("Ramphocaenus melanurus", "Curruca Picuda",188),
    ("Polioptila plumbea", "Curruca Tropical",189),
    ("Donacobius atricapilla", "Sinsonte Laguner",190),
    ("Turdus leucomelas", "Zorzal sabiá",191),
    ("Turdus grayi", "Zorzal pardo",191),
    ("Turdus ignobilis", "Zorzal piquinegro",191),
    ("Mimus gilvus", "Cenzontle tropical",192),
    ("Nemosia pileata", "Cachaquito gigante",193),
    ("Eucometis penicillata", "Tangara cabecigrís",194),
    ("Tachyphonus luctuosus", "Frutero negro",195),
    ("Tachyphonus rufus", "Frutero chocolatero",195),
    ("Ramphocelus dimidiat", "Tangara dorsiroja",196),
    ("Thraupis episcopus", "Azulejo Común",197),
    ("Thraupis glaucocolpa", "Azulejo verdeviche",197),
    ("Thraupis palmarum", "Azulejo Palmero",197),
    ("Conirostrum leucogenys", "Picocono orejiblanco",198),
    ("Conirostrum bicolor", "Conirrostro manglero",198),
    ("Coereba flaveola", "Mielero Común",199),
    ("Tiaris bicolor", "Semillerito bicolor",200),
    ("Saltator maximus", "Saltátor Oliva",201),
    ("Saltator coerulenscens", "Saltador papayero",201),
    ("Saltator striatipectus", "Saltádor Pío-Judío",201),
    ("Sicalis citrina", "Canario coliblanco",202),
    ("Sicalis flaveola", "Canario Coronado",202),
    ("Volatinia jacarina", "Semillero volatinero",203),
    ("Sporophila intermedia" ,"Espiguero Gris",204),
    ("Sporophila bouvronides", "Espiguero de Lesson",204),
    ("Sporophila minuta", "Espiguero Ladrillo",204),
    ("Arremonops conirostris", "Pinzón Conirrostro",205),
    ("Arremon schlegeli", "Pinzón Alidorado",206),
    ("Coryphospingus pileatus", "Soldadito capirotado",207),
    ("Piranga rubra", "Piranga Roja",208),
    ("Piranga olivacea", "Piranga Escarlata",208),
    ("Habia fuscicauda", "Tangara hormiguera gorjirroja",209),
    ("Pheucticus ludovicianus", "Picogordo Degollado",210),
    ("Cyanocompsa cyanoides", "Picogordo Negro",211),
    ("Spiza americana", "Arrocero americano",212),
    ("Vermivora peregrina", "Reinita Verderona",213),
    ("Dendroica petechia", "Reinita de manglar",214), 
    ("Dendroica striata", "Reinita Rayada",214),
    ("Dendroica castanea", "Reinita castaña",214),
    ("Dendroica fusca", "Reinita Naranja",214),
    ("Mniotilta varia", "Chipe Trepador",215),
    ("Setophaga ruticilla", "Candelita norteña",216),
    ("Protonotaria citrea", "Reinita Protonotaria",217),
    ("Seiurus aurocapillus", "Gavilán Pollero",218),
    ("Seiurus noveboracensis", "Reinita acuática",218),
    ("Seiurus motacilla", "Chipe de agua sureño",218),
    ("Psaracolius decumanus", "Oropéndola Crestada",219),
    ("Icterus spurius", "Calandria café",220),
    ("Icterus auricapillus", "Turpial Cabecirrojo",220),
    ("Icterus chrysate", "Turpial Montañero",220),
    ("Icterus galbula", "Turpial de Baltimore",220),
    ("Icterus nigrogularis", "Turpial Amarillo",220),
    ("Icterus mesomelas", " Turpial coliamarillo",220),
    ("Chrysomus icterocephalus", "Turpial Cabeciamarillo",221),
    ("Molothrus oryzivorus", "Chamon Gigante",222),
    ("Molothrus aeneus", "Vaquero de ojos rojos",222), 
    ("Molothrus bonariensis", "Chamón Parásito",222),
    ("Quiscalus lugubris", "Chango Llanero",222),
    ("Quiscalus mexicanus", "Chango Común",222),
    ("Sturnella magna", "Turpial oriental",223),
    ("Sturnella militaris", "Chirlobirlo",223),
    ("Euphonia trinitatis", "Eufonia de Trinidad",225),
    ("Euphonia laniirostris", "Eufonia piquigruesa",225),
    ("Ortalis ruficauda", "Guacharaca culirroja",8),
    ("Elanoides forficatus", "Gavilán tijerilla",226),
    ("Buteo brachyurus", "Águila rabicorta",227),
    ("Buteo albonotatus", "Águila gallinaza",227),
    ("Fulica americana", "Focha Común",228),
    ("Recurvirostra americana", "Avoceta americana​",229),
    ("Limnodromus scolopaceus B", "Agujeta escolopácea",230),
    ("Patagioenas plumbea", "Paloma plomiza",231),
    ("Ara chloroptera", "Guacamayo rojo",232),
    ("Forpus conspicillatus", "Cotorrita de anteojos",233),  
    ("Chordeiles minor", "Añapero yanqui",234),
    ("Colibri delphinae", "Colibrí pardo",235),
    ("Phaethornis augusti", "Ermitaño gris",236),
    ("Phaethornis longirostris", "Ermitaño colilargo norteño",236),
    ("Phaethornis superciliosus ", "Ermitaño colilargo común",236),
    ("Chlorostilbon mellisugus", "Colibrí esmeralda",237),
    ("Certhiaxis mustelinus", "Rastrojero Pechiblanco",137),
    ("Elaenia chiriquensis", "Elaenia Copetona",141),
    ("Elaenia frantzii" , "Elaenia Montañera",141),
    ("Zimmerius vilissimus", "Mosquerito Cejas Blancas",145),
    ("Inezia tenuirostris", " piojito picofino​",148),
    ("Contopus virens", "Picoplano Oliváceo",156),
    ("Contopus cinereus", "Pibí Tropical",156),
    ("Myiarchus crinitus ", "Atrapamoscas Crestado",168),
    ("Atticora melanoleuca", "Golondrina acollarada",178),
    ("Pygochelidon cyanoleuca", "Golondrina Blanquiazul",179),
    ("Petrochelidon pyrrhonota", "Golondrina risquera",238),
    ("Turdus leucomelas", "Mirla Ventriblanca",191),
    ("Turdus ignobilis", "Mirla Ollera",191),
    ("Tachyphonus rufus ", "Frutero Negro",195),
    ("Tiaris bicolor", "semillero bicolor",200),
    ("Sicalis citrina", "Jilguero Cola Blanca",202),
    ("Sporophila schistacea", "Espiguero Pizarra",239),
    ("Coryphospingus pileatus", "Cardonero Coronirrojo",207),
    ("Piranga olivacea", "Tangara escarlata",208),
    ("Vermivora peregrina", "Reinita verderona",213),
    ("Dendroica castanea", "Reinita castaña",214),
    ("Dendroica fusca", "Reinita naranja",214),
    ("Mniotilta varia", "Chipe trepador",215),
    ("Quiscalus lugubris", "Chango Llanero",223),
    ("Sturnella magna", "turpial oriental",224);